app:
  description: Welcome to ${spring.application.name}
db:
  connection: "{connectionString: 'http://___', userName: 'user', password: 'pass'}"
  host: 127.0.0.1
  port: 1200
management:
  endpoints:
    web:
      exposure:
        include: '*'
server:
  port: 8082
spring:
  application:
    name: movie-info-service

  profiles:
    active: local
    
tmdb:
  api:
    key: 5e4ee85b9fbc1138a5a780841315a183
    url: https://api.themoviedb.org/3/movie/
